name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt install zlib1g
    - name: make
      run: make
    - name: build
      run: make build
    - name: clean
      run: make clean
