name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -name: zlib
      run: sudo apt install zlib1g
    - name: cryptopp
      run: |
        wget https://github.com/weidai11/cryptopp/releases/download/CRYPTOPP_8_6_0/cryptopp860.zip
        unzip cryptopp860.zip -d cryptop
        make static dynamic cryptest.exe
        cryptest.exe v
        make libcryptopp.a libcryptopp.so cryptest.exe
        sudo make install PREFIX=/usr/local
    - name: configure
      run: git submodule update --init --remote
    - name: make
      run: make
    - name: build
      run: make build
    - name: test
      run: make test
    - name: clean
      run: make clean
